# Generated by Django 6.1 on 2026-08-13 17:03

import nomina.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colillapago',
            name='anio',
            field=models.IntegerField(default=nomina.models.get_current_year),
        ),
    ]
