# Generated by Django 6.1 on 2026-08-12 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('COLABORADOR', 'Colaborador')], default='COLABORADOR', max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('ip_dispositivo', models.GenericIPAddressField(blank=True, null=True)),
                ('estado_ingreso', models.CharField(choices=[('A_TIEMPO', 'A Tiempo'), ('RETARDO', 'Retardo')], default='A_TIEMPO', max_length=50)),
                ('alerta_reincidencia_activa', models.BooleanField(default=False)),
                ('tipo_permiso', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_permiso', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=50, null=True)),
                ('incapacidad_presentada', models.BooleanField(default=False)),
                ('horas_normales', models.FloatField(default=0)),
                ('horas_extras', models.FloatField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('foto_captura', models.ImageField(blank=True, null=True, upload_to='capturas_faciales/')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='asistencia.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='asistencia.colaborador')),
            ],
        ),
    ]
