# Generated by Django 6.1 on 2026-08-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_solicitudpermiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
