# Generated by Django 6.1 on 2026-08-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_colaborador_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='numero_contacto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
