# Generated by Django 6.1 on 2026-08-13 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_colaborador_numero_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
