# Generated by Django 6.1 on 2026-08-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_colaborador_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='jefe_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='asistencia.colaborador'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='salario_base',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
