# Generated by Django 6.1 on 2026-08-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_colaborador_area_colaborador_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
    ]
