# Generated by Django 6.1 on 2026-08-20 21:53

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.utils import timezone

def reset_default_admin(apps, schema_editor):
    Colaborador = apps.get_model('asistencia', 'Colaborador')
    try:
        admin = Colaborador.objects.get(cedula='999999999')
        admin.password = make_password('admin123')
        admin.rol = 'ADMINISTRADOR'
        admin.estado = 'ACTIVO'
        admin.save()
    except Colaborador.DoesNotExist:
        Colaborador.objects.create(
            cedula='999999999',
            nombre='Administrador Principal',
            rol='ADMINISTRADOR',
            password=make_password('admin123'),
            estado='ACTIVO',
            fecha_ingreso=timezone.now().date(),
            area='DIRECCION',
            cargo='ADMINISTRADOR DEL SISTEMA'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_create_default_admin'),
    ]

    operations = [
        migrations.RunPython(reset_default_admin),
    ]
