# Generated by Django 6.1 on 2026-08-12 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaDisciplinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('GRAVE', 'Grave')], max_length=20)),
                ('descripcion', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='disciplinario/')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CONTRATO', 'Contrato'), ('ID', 'Documento de Identidad'), ('CERTIFICADO_SALUD', 'Certificado de Salud'), ('OTROS', 'Otros')], max_length=50)),
                ('archivo', models.FileField(upload_to='expedientes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=4)),
                ('feedback', models.TextField()),
                ('fecha_evaluacion', models.DateField(default=django.utils.timezone.now)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.colaborador')),
            ],
        ),
    ]
