# Generated by Django 6.1 on 2026-08-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actadisciplinaria',
            name='anio_relacionado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actadisciplinaria',
            name='semana_relacionada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actadisciplinaria',
            name='gravedad',
            field=models.CharField(choices=[('LEVE', 'Leve'), ('GRAVE', 'Grave'), ('MUY_GRAVE', 'Muy Grave')], max_length=20),
        ),
    ]
